# Generated by Django 5.1.2 on 2025-01-16 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('team_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('birthplace', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='baseball_app.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PitchingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('team_name', models.CharField(max_length=50)),
                ('era', models.FloatField()),
                ('appearances', models.IntegerField()),
                ('complete_games', models.IntegerField()),
                ('shutouts', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('win_percentage', models.FloatField()),
                ('innings_pitched', models.FloatField()),
                ('hits_allowed', models.IntegerField()),
                ('home_runs_allowed', models.IntegerField()),
                ('strikeouts', models.IntegerField()),
                ('strikeouts_per_9', models.FloatField()),
                ('walks_allowed', models.IntegerField()),
                ('hit_batters', models.IntegerField()),
                ('wild_pitches', models.IntegerField()),
                ('balks', models.IntegerField()),
                ('runs_allowed', models.IntegerField()),
                ('earned_runs', models.IntegerField()),
                ('k_bb_ratio', models.FloatField()),
                ('whip', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_stats', to='baseball_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('team_name', models.CharField(max_length=50)),
                ('avg', models.FloatField()),
                ('games', models.IntegerField()),
                ('at_bats', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('doubles', models.IntegerField()),
                ('triples', models.IntegerField()),
                ('home_runs', models.IntegerField()),
                ('total_bases', models.IntegerField()),
                ('runs_batted_in', models.IntegerField()),
                ('runs_scored', models.IntegerField()),
                ('strikeouts', models.IntegerField()),
                ('walks', models.IntegerField()),
                ('hit_by_pitch', models.IntegerField()),
                ('sacrifices', models.IntegerField()),
                ('sacrifice_flies', models.IntegerField()),
                ('stolen_bases', models.IntegerField()),
                ('on_base_percentage', models.FloatField()),
                ('slugging_percentage', models.FloatField()),
                ('OPS', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='baseball_app.player')),
            ],
        ),
    ]
