# Generated by Django 5.1.2 on 2025-01-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='jersey_number',
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('投手', '投手'), ('野手', '野手'), ('外野手', '外野手')], max_length=20),
        ),
    ]
