# Generated by Django 5.1.2 on 2025-01-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0002_remove_player_jersey_number_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('投手', '投手'), ('内野手', '内野手'), ('外野手', '外野手')], max_length=20),
        ),
    ]
