# Generated by Django 5.1.2 on 2025-01-16 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0004_player_jersey_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingstats',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1903), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='pitchingstats',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1903), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
