# Generated by Django 5.1.2 on 2025-01-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0007_alter_pitchingstats_k_bb_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstats',
            name='innings_pitched',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
