# Generated by Django 5.1.2 on 2025-01-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0009_alter_pitchingstats_innings_pitched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchingstats',
            name='era',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
