# Generated by Django 5.1.2 on 2025-01-31 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_app', '0011_alter_pitchingstats_k_bb_ratio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pitchingstats',
            name='whip',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
