# Generated by Django 5.1.2 on 2025-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('team_name', models.CharField(max_length=100, verbose_name='チーム')),
                ('avg', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='打率')),
                ('games', models.IntegerField(verbose_name='試合数')),
                ('home_runs', models.IntegerField(verbose_name='本塁打')),
                ('runs_batted_in', models.IntegerField(verbose_name='打点')),
                ('on_base_percentage', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='出塁率')),
                ('slugging_percentage', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='長打率')),
                ('OPS', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='OPS')),
            ],
            options={
                'verbose_name': '打撃成績',
                'verbose_name_plural': '打撃成績',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='PitchingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('team_name', models.CharField(max_length=100, verbose_name='チーム')),
                ('era', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='防御率')),
                ('appearances', models.IntegerField(verbose_name='登板')),
                ('wins', models.IntegerField(verbose_name='勝利')),
                ('losses', models.IntegerField(verbose_name='敗戦')),
                ('strikeouts', models.IntegerField(verbose_name='奪三振')),
                ('whip', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='WHIP')),
                ('innings_pitched', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='投球回')),
            ],
            options={
                'verbose_name': '投手成績',
                'verbose_name_plural': '投手成績',
                'ordering': ['-year'],
            },
        ),
    ]
